apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-users
  labels: 
    app: udagram-api-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-users
  template:
    metadata:
      labels:
        app: udagram-api-users
    spec:
      containers:
      - name: udagram-api-users
        imagePullPolicy: Always
        image: 998443328643.dkr.ecr.us-east-1.amazonaws.com/udagram-api-users:latest
        ports:
          - containerPort: 8080
